services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "supermarket"
    ports:
      - "3306:3306"
    networks:
      - nuvolang_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuvolang_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/supermarket"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "0000"
    networks:
      - nuvolang_network

networks:
  nuvolang_network:
    driver: bridge
